version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ./movies_dataset:/var/www/storage/app/movies 

  horizon:
    volumes:
      - .:/var/www
      - ./movies_dataset:/var/www/storage/app/movies 

  ai_api:
    volumes:
      - .:/var/www
      - ./movies_dataset:/var/www/storage/app/movies 

  nginx:
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx-local:/etc/nginx/conf.d
