version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-reels-app
    container_name: ai_reels_app
    restart: unless-stopped
    working_dir: /var/www
    env_file: .env
    volumes:
      - .:/var/www
      - ./movies_dataset:/var/www/storage/app/movies 
    networks:
      - ai-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  horizon:
    image: ai-reels-app
    container_name: ai_reels_horizon
    restart: unless-stopped
    working_dir: /var/www
    env_file: .env
    command: ["queue", "horizon"]
    volumes:
      - .:/var/www
      - ./movies_dataset:/var/www/storage/app/movies 
    networks:
      - ai-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      app:
        condition: service_started

  nginx:
    image: nginx:alpine
    container_name: ai_reels_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www
    networks:
      - ai-network
    depends_on:
      - app

  ai_api:
    image: ai-reels-app
    container_name: ai_reels_python_api
    restart: unless-stopped
    working_dir: /var/www
    env_file: .env
    command: ["api"]
    ports:
      - "8001:8001"
    volumes:
      - .:/var/www
      - ./movies_dataset:/var/www/storage/app/movies
    networks:
      - ai-network
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:alpine
    container_name: ai_reels_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - ai-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: mysql:8.0
    container_name: ai_reels_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ai_reels_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ai-network
    ports:
      - "3307:3306"
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ai-network:
    driver: bridge

volumes:
  dbdata:
  redis_data:
