name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            kaziomar/snapclip-reels:latest
            kaziomar/snapclip-reels:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file from GitHub Secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Copy Compose, Nginx and Env files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "docker-compose.yml,nginx/,.env"
          target: "/home/${{ secrets.SSH_USERNAME }}/snapclip-reels"
          overwrite: true

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e
            cd /home/${{ secrets.SSH_USERNAME }}/snapclip-reels
            # Login to docker hub on the server in case the repo is private
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            # Force pull the latest image from Docker Hub
            docker compose -f docker-compose.yml pull
            # Restart the services with the new image
            docker compose -f docker-compose.yml up -d
            # Optional: Clean up old unused images to save VM space
            docker image prune -f
